Update the script for CI: if a new crate was added, please add it into the CI script.

diff --git a/.circleci/loop_crates_to_run b/.circleci/loop_crates_to_run
--- a/.circleci/loop_crates_to_run
+++ b/.circleci/loop_crates_to_run
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-set -xe
+set -xe -o pipefail
 
 CARGO_COMMAND=
 
@@ -8,6 +8,27 @@ FEATURES_FOR_PUBSUB="rabbitmq zeromq kafka"
 FEATURES_FOR_HASH="sha3hash blake2bhash sm3hash"
 FEATURES_FOR_CRYPT="secp256k1 ed25519 sm2"
 FEATURES_FOR_HASH_AND_CRYPT=("secp256k1 sha3hash" "ed25519 blake2bhash" "sm2 sm3hash")
+
+CRATES_HAVE_RUN=".crates.have-run"
+
+function check_crates_list () {
+    find . -maxdepth 1 -mindepth 1 -type d \
+            | xargs -I {} basename {} \; \
+            | grep -v "^[.]" \
+            | grep -v "^target$" \
+            | while read crate; do
+        if [ $(grep -c "${crate}" "${CRATES_HAVE_RUN}") -eq 0 ]; then
+            echo "[Error] A new crate [${crate}] was added but did not added into this script [$0]."
+            exit 1
+        fi
+    done
+    rm "${CRATES_HAVE_RUN}"
+}
+
+function record_crate_for_check () {
+    crate="${1}"
+    echo "${crate}" >> "${CRATES_HAVE_RUN}"
+}
 
 function cargo_run_build () {
     CARGO_COMMAND="cargo test --no-run"
@@ -28,6 +49,7 @@ function cargo_run () {
     cd "${crate}"
     ${CARGO_COMMAND} "$@"
     cd "${currdir}"
+    record_crate_for_check "${crate}"
 }
 
 function cargo_run_all () {
@@ -35,6 +57,7 @@ function cargo_run_all () {
     [ -z "${CARGO_COMMAND}" ] && exit 1
 
     cargo_run bigint
+    cargo_run panic_hook
 
     cargo_run worker
     cargo_run error
@@ -79,7 +102,11 @@ function cargo_run_all () {
 }
 
 function main () {
+    local currdir=$(pwd)
+    : > "${CRATES_HAVE_RUN}"
     cargo_run_$1
+    cd "${currdir}"
+    check_crates_list
 }
 
 main "$@"
